#!/bin/zsh
if [[ "$1" == "status" && "$@" != *"--help"* && "$@" != *"-h"* ]];
then
    shift 1; echo_bar - 100;
    command git --git-dir=$HOME/.dot/.git --work-tree=$HOME branches $@
    echo_bar - 100;
    command git --git-dir=$HOME/.dot/.git --work-tree=$HOME status $@
else
    command git --git-dir=$HOME/.dot/.git --work-tree=$HOME $@
fi
