#!/bin/zsh

local cmd="/usr/bin/git"

if [[ "$1" == "status" && "$@" != *"--help"* && "$@" != *"-h"* ]];
then
    shift 1;
    echo-bar - 66;
    command $cmd --git-dir=$HOME/.dot/.git --work-tree=$HOME branches $@
    echo-bar - 66;
    command $cmd --git-dir=$HOME/.dot/.git --work-tree=$HOME status $@
else
    command $cmd --git-dir=$HOME/.dot/.git --work-tree=$HOME $@
fi
return 0
