#!/bin/zsh
local cmd="/usr/bin/git"

if [ ! -d .git ]; then
    $cmd $@
    return 1
fi;

if [[ ($1 == "status" || $1 == "branch")
       && $@ != *"--help"* && $@ != *"-h"* && $@ != *"help"* ]];
then
    echo-bar - 50;
    $cmd branches
    echo-bar - 50;
    $cmd status
else
    $cmd $@
fi;
return 0
