#!/usr/bin/env zsh
# Script to unload and reload LaunchAgents via full plist path
# [opts]
# -R will clear the log file

if [[ $# -lt 1 ]]; then
    return
else 
fi;

local doReset=1
# handle calling from aliases and manually
local receivedCmd="$1"
if [[ "$receivedCmd" = "-r" ]]; then
    receivedCmd="$2"
    doReset=0
elif [[ $2 = "-r" ]]; then
    doReset=0
fi;

local cmdPath=$receivedCmd
local cmdDir=${cmdPath%/*}
local cmdFname=${cmdPath##*/}
local serviceLabel=${cmdFname%.plist}
local serviceState=$(launchctl list | grep $serviceLabel)


# over-thinking it, wc -l was returning "       1" and I thought launchctl list was doing that.
# local serviceState=$(launchctl print gui/$(id -u) | grep $serviceLabel)
# isDisabled=${isDisabled##*> } for print-disabled
# serviceState=${serviceState##*= } # for print 

res="$(date)"

if [ "$serviceState" != "" ]; then
    echo "Unloading" $serviceLabel
   launchctl unload $cmdPath
   echo "launchctl unload $cmdPath"
   res="$res\nlaunchctl unload $cmdPath"
else
fi;

sleep 0.01
echo "launchctl load -w $cmdPath"
res="$res\nlaunchctl load -w $cmdPath"
if [[ $doReset == 0 ]];
then
        echo $res > ~/.log/launchctl;
else
        echo $res >> ~/.log/launchctl
fi;
launchctl load -w $cmdPath
