#!/bin/zsh

# Launch the postgres instance conditionally
# Used in a launchagent plist file to run conditionally


# initial try:
# new_term pg_ctl -l $PGDATA/log start; tail -f $PGDATA/log

#if /opt/homebrew/opt/postgresql@15/bin/pg_ctl status 1> /dev/null ; then
#    # Server is running, therefore do not start a new one
#    echo "pg-startup: server is running, no action"
#    return 1
# else
    echo "pg-startup: no server running, beginning boot" $(id -u) $(whoami)
    /opt/homebrew/opt/postgresql@15/bin/pg_ctl \
        -D /Users/zooey/Documents/code/site/db/postgres/database \
        -U zooey \
        --log=/Users/zooey/.log/pg \
        start
    # pg_ctl -l /Users/zooey/.log/pg start
    # ooo, "tailing" the file makes sense :-0 i are detective
    /usr/bin/tail -f /Users/zooey/.log/pg
    return 0;
# fi;
