#!/bin/zsh
# http://invisible-island.net/xterm/ctlseqs/ctlseqs.html
usage() { echo "Usage: $0 [row] [col]" 1>&2; return 1; }

height=$LINES
y=$2
y=$(( $y > 1900 ? 1900 : y ))
y=$(( $y < 0 ? 0 : y ))

width=$COLUMNS
x=$1
x=$(( $x > 2000 ? 2000 : x ))
x=$(( $x < 0 ? 0 : x ))

if [ -z "${x}" ] || [ -z "${y}" ]; then
    usage
fi

printf 'x=%d, y=%d' x y
printf '\e[8;%d;%dt' y x



# For example, this shell command will set the window to 100x50 characters:
# 
# printf '\e[8;50;100t'
# 
# Minimize the window for a few seconds, then restore it:
# 
# printf '\e[2t' && sleep 3 && printf '\e[1t'
# 
# Move the window to the top/left corner of the display:
# 
# printf '\e[3;0;0t'
# 
# Zoom the window:
# 
# printf '\e[9;1t'
# 
# Bring the window to the front (without changing keyboard focus):
# 
# printf '\e[5t'
