#!/bin/zsh
# 2023-05-28: Mostly a learning experience with zsh/gnu,
#             Could definitely be improved - pretty slow (probably because I'm evaling each ps >_>

# eval ps auxww
# user, pid, %cpu, %me, virtualsize, rss, tt, stat, start, time, command
# Note - if you really want the args, you need ps auxww. But this doesn't have the etime..

RES=""
FRONTEND=$(
    eval ps -o user,pid,%cpu,%mem,vsize,rss,tt,stat,start,utime,etime,command |
        grep '[npm] run start' |
        tr -s " " | cut -f $(printf "1,2,3,4,5,6,7,8,9,10,11,12") -d " "
)
PROC_CT=$(echo $FRONTEND | ag '\n' | wc -l);
if [[ PROC_CT == 0 && $1 != 1 ]]; then return 0
fi;

if [[ "$FRONTEND" == *"npm"* ]];    
then
    for i in $(seq 1 $PROC_CT)
    do
        # Handle two nodemon processes
        ID=$((i))
        IDX=''
        if [[ $ID > 1 ]];
        then IDX="[$ID]"; fi;
        PID=$(echo $FRONTEND | cut -f 2 -d " " | tr -s "\n" "," | cut -f $ID -d ",")
        START=$(echo $FRONTEND | cut -f 9 -d " " | tr -s "\n" ","  | cut -f $ID -d ",")
        CMD=$(echo $FRONTEND | cut -f 12 -d " " | tr -s "\n" ","  | cut -f $ID -d ",")
        ETIME=$(echo $FRONTEND | cut -f 11 -d " " | tr -s "\n" ","  | cut -f $ID -d ",")
        if [[ $ID > 1 ]]; then RES="$RES\n"; fi;
        RES="$RES<< Frontend"$IDX" >> ("$PID") since ["$START"] for "$ETIME
    done;
    if [[ $1 ]]; then echo $RES; fi;
    return 0;
else
    if [[ $1 ]]; then
        echo '<< Frontend offline >> -> cd $SITEPATH; npm run start'
    fi;
    return 1;
fi;

